<?php
define('tag_cloud_tname','3D标签云');
define('tag_cloud_width','200');
define('tag_cloud_height','200');
define('tag_cloud_tcolor','0xbd1016');
define('tag_cloud_tcolor2','0x808080');
define('tag_cloud_hicolor','0x0065ff');
define('tag_cloud_bgcolor','#f3f3f3');
define('tag_cloud_tspeed','100');
define('tag_cloud_trans','transparent');
define('tag_cloud_args','');
define('tag_cloud_compmode','false');
define('tag_cloud_showwptags','true');
define('tag_cloud_mode','tags');
?>